apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.project_id | dump }}
  annotations:
    "backstage.io/project": ${{ values.project_id | dump }}
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
