apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cloudrun-service-template
  title: Cloud Run Service Template
  description: An example template that creates a simple cloudrun service
  tags:
    - backstage
spec:
  owner: user:guest
  type: service

  parameters:
    - title: New cloudrun Service
      required:
        - project_id
      properties:
        project_id:
          title: Project Name
          type: string
          description: Name of the Project to deploy the Cloud Run
          ui:autofocus: true
          ui:options:
            rows: 5

  steps:
    - name: Read Environment
      id: environment
      action: humanitec:get-environment

    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        targetPath: ./content
        url: ./content
        values:
          project_id: ${{ parameters.project_id }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        defaultBranch: main
        description: This is cloud run in ${{ parameters.project_id }}
        repoUrl: github.com?owner=monkmantra&repo=${{ parameters.project_id }}
        repoVisibility: public
        protectDefaultBranch: false
        oidcCustomization: ${{ steps.environment.output.githubOIDCCustomization }}

    # - id: humanitec-create-app
    #   name: Create Humanitec App
    #   action: humanitec:create-app
    #   input:
    #     appId: ${{ parameters.project_id }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
